---
title: "Datos ordinales"
author: "Heiner Romero Leiva"
date: "9/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Datos Ordinales

Ejemplo:

```{r}
notas = c("S", "N", "A", "Ex", "N", "S", "Ex", "N", "S", "S", "A", "N", "A", "A", "A", "N")

fabs = table(notas) # Frecuencia absoluta
fabs # frecuencia absoluta 
prop.table(fabs) # frecueencia relativa 
cumsum(fabs) # frecuencias absolutas acumuladas notas deficientes 5, notas malas o inferiores 7, notas normales o inferiores 12  y notas suficientes o inferiores 16.   
cumsum(prop.table(fabs)) # frecuencias relativas acumuladas

# Graficacion 
barplot(fabs, main = "Diagrama de barras de frecuencias absolutas")
barplot(cumsum(fabs), ylim = c(0,20),main = "Diagrama de barras de frecuencias relativas acumuladas")

```

### Frecuencias relativas acumuladas 

```{r}

cumsum(table(notas))/length(notas) # Frecuencias relativas acumuladas 

cumsum(table(notas)/length(notas)) # Frecuencias relativas acumuladas 

# Nunca

prop.table(cumsum(table(notas))) # queda prohibido hacer esto y esta mal. 

```

### Tablas bidimensionales

```{r}
# apply(table(datos), margin = ..., fun = cumsum())

# t(apply(table(datos), margin = ..., fun = cumsum()))

# Graficacion acumulada

# Diagrama = apply(prop.table(fabs), margin = 1), margin  = 1, FUN = consum) 
# barplot(Diagrama, beside = TRUE, legend = TRUE, main " (...)", args.legend = list(x = "topleft", cex = 0.55))
              
```

### Ejemplo completo

```{r}
crabs = read.table("/Users/heinerleivagmail.com/Documents/GitHub/r-basic/data/datacrab.txt", header = TRUE)
crabs = crabs[, -1] # Omitimos la primera columna # data wrangling
str(crabs)

table(crabs$width)

# Convirtiendo variable numerica a variable ordinal

intervalos = cut(crabs$width, breaks = c(21,25,29,33, Inf), right = FALSE, 
                 labels = c("21-25", "25-29", "29-33", "33-..."))

crabs$width.rank = ordered(intervalos)

str(crabs)

# Tabla bidimensional 
tabla = table(crabs[,c(1,6)]) # color filas y las columnas son los rangos
tabla

# Frecuencia relativa marginal por filas
relativa = round(prop.table(tabla, margin =1), 3)
relativa

# Frecuencia relativa acumulada

acumulada = round(apply(prop.table(tabla, margin = 1), MARGIN = 1, FUN = cumsum), 3)

t(acumulada) # frecuencia relativa acumulada por filas

azul = c("cyan", "cyan4", "cyan1", "cyan3") # mucho cuidado con los vectores de colores

# Diagrama de frecuencias relativas
barplot(t(relativa), beside = TRUE, legend = TRUE, ylim = c(0,1), col = azul, main = "Diagrama de barras de frecuencias relativas", args.legend=list(x= "topright", cex=0.55))
                                                          
# Diagrama de frecuencias relativas acumuladas 
barplot(acumulada, beside = TRUE, legend = TRUE,  col = azul, main = "Diagrama de barras de frecuencias relativas", args.legend=list(x= "topleft", cex=0.55))

#  Analisis: a mayor numero de colores los cangrejos tienden a ser mas pequennos




```


