---
title: "Datos Cualitativos ejercicio completo"
author: "Heiner Romero Leiva"
date: "9/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Ejemplo final

### Juntar color de ojos y pelo sin distinguir por sexo

```{r}
ftable(HairEyeColor) # tabla original 

male = HairEyeColor[, ,"Male"] # extrayendo solo la informacion del hombre. 
female = HairEyeColor[, , "Female"] # extrayendo solo la informacion de la mujer

data = as.table(male+female)

data

```

### Manipulacion de datos

```{r}
dimnames(data) = list(
  Pelo = c("Negro", "Marron", "Pelirrojo", "Rubio"),
  Ojos = c("Cafes", "Azules", "Miel", "Verdes")
)

data # tabla convertida a espannol

```

### Diagrama de Mosaico

```{r}
plot(data, col = c("green", "lightblue"), main = "Diagrama de Mosaico")
```

### Datos Numericos

```{r}
sum(data)
```

### Tablas de frecuencias absolutas y relativas de cada variable

```{r}
colSums(data) # absoluta
rowSums(data) # absoluta

round(prop.table(colSums(data)),3) # relativa
round(prop.table(rowSums(data)),3) # relativa


```

### Diagramas de barras
```{r}

barplot(prop.table(colSums(data)), ylim = c(0, 0.4), 
        main = "Frecuencias relativas del color de ojos", 
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"))

barplot(prop.table(rowSums(data)), ylim = c(0, 0.5), 
        main = "Frecuencias relativas del colores de cabello", 
        col = c("black", "burlywood4", "red", "gold"))

```

### Frecuencias relativas globales y marginales

```{r}

round(prop.table(data),3) # frecuencia relativa global
round(prop.table(data, margin = 1), 3) # frecuencia relativa marginal por filas
round(prop.table(data, margin = 2), 3) # frecuencias relativa marginal por columnas

# CrossTable(data) # resumen

```

### Diagrama en bloque
```{r}
barplot(prop.table(data, margin = 1), beside = TRUE,  
        ylim = c(0, 0.8),
        legend.text = TRUE, 
        col = c("black", "burlywood4", "red", "gold"), 
        main = "Frecuencias relativas del color de pelo \n para cada color de ojo")

barplot(t(prop.table(data, margin = 2)), beside = TRUE,  
        ylim = c(0, 0.6),
        legend.text = TRUE, 
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"), 
        main = "Frecuencias relativas del color de ojos \n para cada color de pelo")
```

