---
title: "Histogramas de Frecuencias"
author: "Heiner Romero Leiva"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Histograma de Frecuencias

```{r}

data = read.table("/Users/heinerleivagmail.com/Documents/GitHub/r-basic/data/datacrab.txt", header = TRUE)

cw = data$width
cw

A = diff(range(cw)) / 10
A

# Como nuestros datos est치n expresados en mm con una precisi칩n de una cifra decimal, debemos redondear por exceso a un cifra decimal el resultado obtenido. Por lo tanto, nuestra amplitud ser치 de 


A = 1.3

L1 = min(cw)-1/2*0.1 # calculando el primer limite
L1

L <- L1 + A*(0:10) # calculando los demas limites de la distribucion
L 

hist(cw, breaks = L, right = FALSE, main = "Histograma de las anchuras de los cangrejos")

```


```{r}
hist(cw, breaks = 11, right = FALSE, plot = FALSE) # visualizando todos los parametros del histograma visualizado. 
```

# Creando Histograma de Frecuencias Absolutas mediante funcion programada

```{r}
histAbs = function(x,L) {
  h = hist(x, breaks = L, right = FALSE, freq = FALSE,
           xaxt = "n", yaxt = "n", col = "lightgray", 
           main = "Histograma de frecuencias absolutas", 
           xlab = "Intervalos y marcas de clase",ylab = "Frecuencias absolutas")
  axis(1, at=L)
  text(h$mids, h$density/2, labels=h$counts, col="purple") 
}

histAbs(cw, L)
rug(jitter(cw))  # agregando los datos que pertenecen a cada una de las distribuciones por debajo y por distribuciones. 

```

# Histograma de Frecuencias Absolutas Acumuladas:

```{r}
histAbsCum = function(x,L) {
  h = hist(x, breaks = L, right = FALSE , plot = FALSE) 
  h$density = cumsum(h$density)
  plot(h, freq = FALSE, xaxt = "n", yaxt = "n", col = "lightgray", 
       main = "Histograma de frecuencias\nabsolutas acumuladas", xlab = "Intervalos", 
       ylab = "Frec. absolutas acumuladas")
  axis(1, at=L)
  text(h$mids, h$density/2, labels = cumsum(h$counts), col = "purple") 
}

histAbsCum(cw, L)
```

# Densidad

```{r}
str(density(cw)) # mas informacion acerca de densidad. 
```

# Histograma de Frecuencias Relativas con curva de densidad estimada

```{r}
histRel = function(x,L) {
  h = hist(x, breaks=L, right=FALSE , plot=FALSE)
  t = round(1.1*max(max(density(x)[[2]]),h$density),2) 
  plot(h, freq = FALSE, col = "lightgray", 
       main = "Histograma de frec. relativas\ny curva de densidad estimada", 
       xaxt="n", ylim=c(0,t), xlab="Intervalos", ylab="Densidades")
  axis(1, at = L) 
  text(h$mids, h$density/2, labels = round(h$counts/length(x),2), col = "blue")
  lines(density(x), col = "purple", lwd = 2) 
}

histRel(cw, L)
rug(jitter(cw))

# Ploteando grafico con distribucion normal para comparar

histRel(cw, L)
curve(dnorm(x, mean(cw), sd(cw)), col = "blue", lty = 4, lwd = 2, add = TRUE)
legend("topright", lwd=c(2,2), lty = c(1,4), col = c("purple", "blue"), legend = c("Densidad estimada", "Densidad normal"))

```

# Histograma de Frecuencias relativas acumuladas con curva de Distribucion estimada
```{r}


histRelCum = function(x,L){
  h = hist(x, breaks = L, right = FALSE , plot = FALSE)
  h$density = cumsum(h$counts)/length(x)
  plot(h, freq = FALSE, 
      main = "Histograma de frec. rel. acumuladas\n y curva de distribuci칩n estimada", 
      xaxt = "n", col = "lightgray", xlab = "Intervalos", 
      ylab = "Frec. relativas acumuladas") 
  axis(1, at = L)
  text(h$mids, h$density/2, labels = round(h$density ,2), col = "blue")
  dens.x = density(x)
  dens.x$y = cumsum(dens.x$y)*(dens.x$x[2]-dens.x$x[1]) 
  lines(dens.x,col = "purple",lwd = 2)
}

histRelCum(cw, L)
rug(jitter(cw))

```
























