---
title: "Tidyverse"
author: "Heiner Romero Leiva"
date: "9/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Tidyverse - Dyplyr

```{r}
iris_petal = select(iris, starts_with("Petal")) # filtrado avanzado 
head(iris_petal)

iris_length = select(iris, ends_with("Length")) # filtrado avanzado 
head(iris_length)

```
#### Subset

```{r}
subset(iris, Species == "setosa") -> setosa
head(setosa, 5)
str(setosa)


subset(iris, Species == "versicolor", select = c(1,3)) -> versicolor
rownames(versicolor) = 1:nrow(versicolor) # con esto nos garantizamos que el DF no va desde 50 a 60 o 70, sino que se reinicia y empieza en 1. 
head(versicolor, 5)
str(versicolor)
```


#### Funciones en Dataframes

```{r}
str(iris)
sapply(subset(iris, select = 1:4), mean) # columna de la 1 a la 4 
# estas formulas son utiles para no hacer ciclos. 

sapply(iris[, 1:4], sum) # todas las filas pero columnas de la 1 a la 4

f = function(x){
  sqrt(sum(x^2))
}

sapply(iris[,1:4], f) # se le aplican a todas las filas de las 4 columnas

```
```{r}
df = data.frame(C1 = c(1,2,NA, 4), C2 = c(5, NA, 2, 3))
sapply(df, mean)
sapply(df, mean, na.rm = TRUE) # recordar remover los NA

```

```{r}
aggregate(cbind(Sepal.Length, Petal.Length) ~ Species, data = iris, FUN = mean, na.rm = TRUE)
# solo estoy tomando las medias de las columnas que tienen lo que estoy definiendo

```
```{r}
head(mtcars)
str(mtcars)

mtcars$cyl = as.factor(mtcars$cyl)
mtcars$gear = as.factor(mtcars$gear)
mtcars$carb = as.factor(mtcars$carb)

str(mtcars)

aggregate(mpg~cyl+gear+carb, data = mtcars, FUN = mean, na.rm = TRUE) # consumo medio del carro (mpg) recordar que esta va adelante del ~ porque es una variable numerica y las variables cualitativas siempre van despues de las ~, creando una nueva variable combinando con otras variables, pero tienen que ser **factores**

# Puedo usar un attach(mtcars) para no estar agregando el signo del dolar por ejemplo: mtcars$mpg
```


